### ISSUE TITLE
Лишние скобки

### ISSUE THREAD

**Issue by Alexmg86** [metaer/Converter#1]
![2015-04-21 11 28 46](https://cloud.githubusercontent.com/assets/7482040/7248329/9a823790-e81a-11e4-968e-523b03bcaad9.png)

В начальном файле идет
{\C256;План 2-го этажа.}

Нам нужен текст 
План 2-го этажа.

У нас сейчас 
###28###
План 2-го этажа.}

**Comment by metaer** [comment]
То есть, получается, правило, что <всё от "\" до ";" включительно не является фразой> не охватывает все случаи. Надо дополнительное правило вводить. Для этого нужно знать - могут ли эти символы "{" и "}" находиться внутри фразы? Или такого ни при каких условиях не может быть?

**Comment by Alexmg86** [comment]
![2015-04-23 18 11 04](https://cloud.githubusercontent.com/assets/7482040/7300324/3fc78a46-e9e4-11e4-844d-c136c74ed57b.png)

  1
{\fArial|b1|i1|c204|p34;пример^Jлиния1\{100мм\}\Pлинии \{100мм\} 2}
 73

Выходит что могут.
Но также получается, что если она в конце закрывается, то обязательно и в начале должна быть.

**Comment by Alexmg86** [comment]
Короче вот как я понял, попробовал разные варианты в автокаде.
Если в начале и в конце есть скобки фигурные, то их можно отметать.
Если фигурная скобка является частью текста, то перед ней идет обратный слеш "\}"

**Comment by metaer** [comment]
Так и не понял, почему здесь нет экранирующих обратных слешей:
1
{\fArial|b1|i1|c204|p34;пример^Jлиния1{100мм}\Pлинии {100мм} 2}}
73

И ещё выходит, что правило "от обратного слеша до точки с запятой" не действует

**Comment by metaer** [comment]
<code>\{</code>

**Comment by metaer** [comment]
Вот кстати что написано по той ссылке про скобки:
{}Braces - define the text area influenced by the code

23 апреля 2015 г., 18:53 пользователь Alexmg86 <notifications@github.com>
написал:

> Короче вот как я понял, попробовал разные варианты в автокаде.
> Если в начале и в конце есть скобки фигурные, то их можно отметать.
> Если фигурная скобка является частью текста, то перед ней идет обратный
> слеш "}"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metaer/Converter/issues/1#issuecomment-95631898>.
>



-- 
С уважением, Павел

**Comment by metaer** [comment]
Определяет текстовое поле, на которое влияет код, если дословно переводить.

Типа что-то связанное с экранированием кода. Хз. Я не совсем врубил
