### ISSUE TITLE
Лишние скобки 2

### ISSUE THREAD

**Issue by Alexmg86** [metaer/Converter#2]
![2015-04-21 12 13 12](https://cloud.githubusercontent.com/assets/7482040/7249170/10700d6e-e821-11e4-9bf7-86bb2469de15.png)

В начальном файле идет
{Стадия}

Нам нужен текст 
Стадия

У нас сейчас 
###1###
{Стадия}

Тут интересный момент, так как он непонятно почему их проставляет. Может мне потестить и попробовать найти закономерность когда берутся скобки, а когда нет?

**Comment by metaer** [comment]
см. https://github.com/metaer/Converter/issues/1

**Comment by metaer** [comment]
Ну если сможешь, попробуй найти закономерность. Можно попробовать программно их не включать во фразы. Подробнее см. https://github.com/metaer/Converter/issues/1

**Comment by Alexmg86** [comment]
Тут видимо очень связано с первым пунктом.
