### ISSUE TITLE
Числа не все нужно отметать

### ISSUE THREAD

**Issue by Alexmg86** [metaer/Converter#3]
![2015-04-21 12 13 42](https://cloud.githubusercontent.com/assets/7482040/7249280/f8634ee2-e821-11e4-94b2-7e15cd038872.png)

В начальном файле идет
 71
     4
 72
     5
  3
{\fArial|b0|i0|c204|p34;\W0.8;\C256;Стадион. \fArial|b0|i0|c0|p34; \fArial|b0|i0|c204|p34;Разрезы по трибунам (оси 1,\fArial|b0|i0|c0|p34; \fArial|b0|i0|c204|p34;2,\fArial|b0|i0|c0|p34; \fArial|b0|i0|c204|p34;3,\fArial|b0|i0|c0|p34; \fArial|b0|i0|c20
  1
4|p34;между \fArial|b0|i0|c0|p34;2\fArial|b0|i0|c204|p34; и \fArial|b0|i0|c0|p34;3; 44\fArial|b0|i0|c204|p34; и 45)}

Нам нужен текст 
Стадион. Разрезы по трибунам (оси 1, 2, 3, между 2 и 3; 44 и 45)}

У нас сейчас 
###36###
Разрезы по трибунам (оси 1,
###37###
между 
###38###
 и 
###39###
 и 45)}

Тут все же лучше не убивать числа, которые идут в контексте фразы. 
Плюс нужно решить. можно ли как-то оставлять фразу единой? или это нарушает логику?
Просто переводить ее так лучше, это будет большим плюсом потом нам, когда человек будет выбирать между нами или той гавнософтиной.
Я сейчас не имею ввиду всякие разрывы и переносы строк, а вот хотя бы такой момент.

**Comment by metaer** [comment]
С числами понял, будет сделано. По поводу неразрывной фразы - это отдельная тема. Кое-что придумал. Отпишу на емэил.

**Comment by metaer** [comment]
Готово
