### ISSUE TITLE
Формат на выходе и кодировка

### ISSUE THREAD

**Issue by Alexmg86** [metaer/Converter#4]
Еще такой момент.
а если делать на выходе не .txt, а вордовский .docx - это сильно усложнит задачу?
Также с кодировкой что-то не то. Я пытался эти txt открыть в ворде и он у меня текст просто рушил странным образом ((

**Comment by metaer** [comment]
docx - да, усложнит задачу. Не знаю пока на сколько сильно, нужно думать. А для чего это нужно?
Какая кодировка выходного файла нужна? UTF-8 ?

**Comment by Alexmg86** [comment]
Это нужно для того чтобы CAT системы не воспринимали теги всякие.
Вот традос например может и с txt работать норм, а вот щас модный облачный мемсорс не хочет работать нормально с ними. Зато docx рулит в этом плане
А кодировка у мну вот так показывается ((( попробуй у себя открыть в ворде.

![2015-04-23 18 24 10](https://cloud.githubusercontent.com/assets/7482040/7300641/01611928-e9e6-11e4-9cac-a48bc8fcd8ba.png)

**Comment by metaer** [comment]
Это не в кодировке дело. А в том, что файлы ворда должны быть специального
формата. Если ты из txt в ворд вставишь и сохранишь, а потом откроешь через
txt, то получишь не тоже самое, что было в начале.

23 апреля 2015 г., 18:24 пользователь Alexmg86 <notifications@github.com>
написал:

> Это нужно для того чтобы CAT системы не воспринимали теги всякие.
> Вот традос например может и с txt работать норм, а вот щас модный облачный
> мемсорс не хочет работать нормально с ними. Зато docx рулит в этом плане
> А кодировка у мну вот так показывается ((( попробуй у себя открыть в ворде.
>
> [image: 2015-04-23 18 24 10]
> <https://cloud.githubusercontent.com/assets/7482040/7300641/01611928-e9e6-11e4-9cac-a48bc8fcd8ba.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metaer/Converter/issues/4#issuecomment-95623957>.
>



-- 
С уважением, Павел

**Comment by metaer** [comment]
Вопрос с кодировкой решен. Принято решение делать пока в UTF-8, а потом возможно добавить выбор пользователем кодировки UTF-16 LE
