### ISSUE TITLE
блоки CONTEXT_DATA не обрабатываются

### ISSUE THREAD

**Issue by metaer** [metaer/Converter#7]
там есть куски рисунков, которые почему-то не идут как MText, а попадают в CONTEXT_DATA{
и идут после надписи 304

например,
"
304
Линия сгиба

"

И это нифига не обрабатывается
Подробнее см. письмо за 04.05.15 17:16

**Comment by Alexmg86** [comment]
Не знаю как сюда приложить файлы.

Вот еще одна закономерность в тех местах
Бывает вот такого плана строки.
Фигурные скобки ставятся, если идет форматирование.
{\H0.83333x;Монолитная ж.-б. опора\Pтолщиной 600 мм}

**Comment by metaer** [comment]
по поводу файлов: можно ссылки на файл писать, а файл куда-нибудь заливать.
Это именно в CONTEXT_DATA ?

**Comment by Alexmg86** [comment]
https://cloud.mail.ru/public/5RzVjCnCsDWQ/Issues%207
Вот тут хорошие примеры. Прям поиском пробивай "CONTEXT_DATA{" и увидишь

**Comment by metaer** [comment]
404 выдало по ссылке

**Comment by metaer** [comment]
из 12.dxf:
строки 36718 - 36870
Там после открывающейся фигурной скобки идут ещё открывающиеся, а потом только закрывающиеся. Вроде по 3 и тех, и тех.

**Comment by Alexmg86** [comment]
из того что ты написал строк, нам нужна только 36744
она идет после символов "304"
Монолитная ж.-б. балка\P1200х1475(h)
вообще я заметил весь текст именно после 304 идет. и кажется что не важно какой он длинны

**Comment by Alexmg86** [comment]
Точно все равно на кол-во символов. Сейчас добавил кучу текста и все они умещаются в один сегмент после 304 строки.
Посмотри, плиз, строки 212728-212756
там кусок текста будет попадать? он как бы и в "CONTEXT_DATA{" попадает и как бы в первый MTEXT.
"Сб. ж.-б. подтрибунная балка \P "

**Comment by metaer** [comment]
По идее и тот и другой нужно выносить

**Comment by metaer** [comment]
подтрибунная \Pбалка - я прочитал сначала "подтрибунная рыбалка". Типа там футбол идет, зрители, а под трибунами ещё и рыбаки сидят, рыбу ловят. По отдельным билетам.

**Comment by Alexmg86** [comment]
Ого. Я тебе расстрою.
Не целиком фразу дергает.
304
{\H0.83333x;###5###\Pподтрибунной балки } 

после "\P" не выдергивает текст "подтрибунной балки" и тому подобные места

304
###6###\Pшириной 1200 мм, переменной высоты\P(1417...1715 мм)

**Comment by metaer** [comment]
Понял. Займусь тогда этим.

7 мая 2015 г., 23:12 пользователь Alexmg86 <notifications@github.com>
написал:

> Ого. Я тебе расстрою.
> Не целиком фразу дергает.
> 304
> {\H0.83333x;###5 <https://github.com/metaer/Converter/issues/5>###\Pподтрибунной
> балки }
>
> после "\P" не выдергивает текст "подтрибунной балки" и тому подобные места
>
> 304
> ###6 <https://github.com/metaer/Converter/issues/6>###\Pшириной 1200 мм,
> переменной высоты\P(1417...1715 мм)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metaer/Converter/issues/7#issuecomment-100003165>.
>



-- 
С уважением, Павел

**Comment by metaer** [comment]
Готово. См. #8

**Comment by metaer** [comment]
Ну и CONTEXT_DATA сейчас выдергивается, так что проблема решена.
